# Generated by Django 2.2.6 on 2020-03-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
